DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS alumnis;
DROP TABLE IF EXISTS configurations;
DROP TABLE IF EXISTS qr_codes CASCADE;
DROP TABLE IF EXISTS scanners;
DROP TABLE IF EXISTS usages;